[tool.pyright]
typeCheckingMode = "strict"
venvPath = "."
venv = ".venv"
# Pyright Rules Overrides
reportMissingFunctionReturnType = "error"
reportUnknownMemberType = "warning"
reportMissingTypeStubs = "warning"

[tool.ruff]
target-version = "py311"
line-length = 88

[tool.ruff.lint]
select = [
    "ARG001", # unused arguments in functions
    "B",      # flake8-bugbear
    "C4",     # flake8-comprehensions
    "E",      # pycodestyle errors
    "F",      # pyflakes
    "I",      # isort
    "N",      # Pep-8 naming
    "UP",     # pyupgrade
    "W",      # pycodestyle warnings
    "ANN201", # Enforce return type declaration in public methods
    "ANN202", # Enforce return type declaration in private methods
]
ignore = [
    "B008", # do not perform function calls in argument defaults
    "B904", # Allow raising exceptions without from e, for HTTPException
    "E501", # line too long, handled by black
    "W191", # indentation contains tabs
    "E731", # Do not assign a `lambda` expression, use a `def`
]

[tool.ruff.lint.pyupgrade]
# Preserve types, even if a file imports `from __future__ import annotations`.
keep-runtime-typing = true


[tool.coverage.report]
include_namespace_packages = true
skip_empty = true
omit = ["**/.venv/*", "**/__init__.py", "**/test/*"]